services:

  postgres:
    image: postgres:16
    container_name: subscriptions_db
    restart: always
    environment:
      POSTGRES_DB: subscriptions_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - subscriptions-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d subscriptions_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: subscriptions-cache
    ports:
      - "6379:6379"
    networks:
      - subscriptions-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: subscriptions-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_NODENAME: rabbit@rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - subscriptions-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 15s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  subscriptions-network:
    driver: bridge